const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(t){const x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2600)}
function scrollTo(id){$(id)?.scrollIntoView({behavior:"smooth",block:"start"})}
$$('[data-scroll]').forEach(b=>b.onclick=()=>scrollTo(b.dataset.scroll)); $("#openAi").onclick=()=>scrollTo("#study"); $("#menuBtn").onclick=()=>toast("لە وەشانی دواتردا مێنیووی تەواو زیاد دەکرێت.");
const langText={ku:"AI مامۆستا بۆ پۆلی 12، زانکۆ و پەیمانگە.",ar:"مساعد تعليمي بالذكاء الاصطناعي للصف 12 والجامعة والمعاهد.",en:"An AI study assistant for Grade 12, university and institute students."};
$("#language").onchange=e=>{let l=e.target.value;document.documentElement.lang=l;document.documentElement.dir=l==='en'?'ltr':'rtl';$("#heroText").textContent=langText[l];toast(l==='ku'?'زمان: کوردی':l==='ar'?'اللغة: العربية':'Language: English')};
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function localAI(q){const s=q.toLowerCase(); if(/نیوتن|newton/.test(s))return "یاسای یەکەمی نیوتن دەڵێت ئەگەر هێزی دەرەکی کاریگەری نەکات، جەستەیەک دۆخی خۆی دەپارێزێت. بۆ نموونە: پاسکیلێک بە هۆی بەرکەوتن و هێزی دەرەکی دەست بە گۆڕینی خێرایی دەکات.\n\n💡 کورتە: هێزی نەخوازراو = گۆڕینی دۆخی جووڵە."; if(/photosynthesis|فۆتۆسینتێز|گەڵا|ڕووەک/.test(s))return "فۆتۆسینتێز پرۆسەیەکە کە ڕووەکەکان بە یارمەتی ڕووناکی، ئاوی و CO₂ خواردن دروست دەکەن و ئۆکسجین دەردەدەن.\n\n1) ڕووناکی دەگیرێت.\n2) ئاوی و CO₂ بەکاردێت.\n3) گلوکۆز و ئۆکسجین دروست دەبێت."; if(/2\s*\+\s*2/.test(s))return "٢ + ٢ = ٤. ئەگەر دەتەوێت، دەتوانم هەمان بیرۆکە بە شێوەی وانەی پۆلی 12 ڕوون بکەمەوە."; return "لە Demo ـی ئێستادا وەڵامی ناوخۆیی بەردەستە. بۆ AI ـی ڕاستەقینە، backend ـی pole12krd پێویستە و API key نابێت لە ناو frontend بخرێت."}
$("#chatForm").onsubmit=async e=>{e.preventDefault();const input=$("#question"),q=input.value.trim();if(!q)return;const chat=$("#chat");chat.insertAdjacentHTML('beforeend',`<div class="bubble user">${escapeHtml(q)}</div>`);input.value="";const thinking=document.createElement('div');thinking.className='bubble bot';thinking.textContent='AI مامۆستا خەریکی بیرکردنەوەیە...';chat.appendChild(thinking);chat.scrollTop=chat.scrollHeight;try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,level:$("#level").value,subject:$("#subject").value,mode:$("#mode").value,language:$("#language").value})});if(!r.ok)throw Error();const d=await r.json();thinking.innerHTML='<b>AI مامۆستا:</b><br>'+escapeHtml(d.answer).replace(/\n/g,'<br>');$("#aiStatus").textContent='AI ـی ڕاستەقینە لە backend ـەوە وەڵام دەدات.';}catch{thinking.innerHTML='<b>AI مامۆستا:</b><br>'+escapeHtml(localAI(q)).replace(/\n/g,'<br>');$("#aiStatus").textContent='ئێستا demo ـی ناوخۆییە؛ backend دابنێ بۆ AI ـی ڕاستەقینە.'}chat.scrollTop=chat.scrollHeight};
let pdfText='';
$("#pdf").onchange=async e=>{const f=e.target.files[0];if(!f)return;$("#fileInfo").textContent=`📄 ${f.name} — ${Math.round(f.size/1024)} KB`;$("#pdfResult").hidden=false;$("#resultContent").textContent='PDF دەخوێندرێتەوە...';try{const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';const data=await f.arrayBuffer(),pdf=await pdfjs.getDocument({data}).promise;let parts=[];for(let i=1;i<=Math.min(pdf.numPages,25);i++){const page=await pdf.getPage(i),c=await page.getTextContent();parts.push(c.items.map(x=>x.str).join(' '));}pdfText=parts.join('\n').replace(/\s+/g,' ').trim();renderSummary();toast(`PDF ـەکە خوێندرایەوە: ${pdf.numPages} لاپەڕە`)}catch(err){console.error(err);$("#resultContent").textContent='نەتوانرا PDF بخوێندرێتەوە. تکایە PDF ـێکی تر تاقی بکەرەوە.'}};
function renderSummary(){const words=pdfText.split(/\s+/).filter(Boolean);const summary=words.length?words.slice(0,180).join(' ')+(words.length>180?' …':''):'دەقی PDF بەتاڵە.';const sentences=(pdfText.match(/[^.!؟]+[.!؟]/g)||[]).slice(0,8);const cards=sentences.slice(0,6).map((x,i)=>`<div class="mini-card"><b>کارت ${i+1}</b><p>${escapeHtml(x.trim())}</p></div>`).join('')||'<p>دەقی کافی بۆ Flashcard نییە.</p>';const quiz=sentences.slice(0,4).map((x,i)=>`<div class="mini-card"><b>پرسیار ${i+1}:</b> ئەم ڕستەیە چی دەڵێت؟<p>${escapeHtml(x.trim())}</p></div>`).join('')||'<p>دەقی کافی بۆ Quiz نییە.</p>';window.studyResults={summary,cards,quiz};$("#resultContent").innerHTML='<h3>کورتکراوە</h3><p>'+escapeHtml(summary)+'</p>'}
$$('[data-tab]').forEach(b=>b.onclick=()=>{if(!window.studyResults)return;const t=b.dataset.tab;$("#resultContent").innerHTML=t==='summary'?'<h3>کورتکراوە</h3><p>'+escapeHtml(window.studyResults.summary)+'</p>':t==='cards'?'<h3>Flashcards</h3>'+window.studyResults.cards:'<h3>Quiz</h3>'+window.studyResults.quiz});
